print("-"*18)
print("Salary Adjustment")
print("-"*18)
name = str(input("Employe's name: "))
salary = float(input("What's the employe salary ? "))
newsalary = salary + (salary*0.15)
print("-"*18)
print("Name: {}\nSalary: R$ {}\nNew salary: R$ {:.2f}".format(name, salary, newsalary))
print("-"*18)
