print("-"*17)
print("Cars' Hire")
print("-"*17)
days = int(input("How many days do you want to hire the car ? "))
kms = float(input("How many kilometers did you drive ? "))
print("-"*17)
totaltopay = (days*60)+(kms*0.15)
print("Value per day: R$ 60\nValue per kilometers driven: R$0.15")
print("Hired days: {}\nDriven kilometers: {}\nTotal value to be paied: R$ {:.2f}".format(days, kms, totaltopay))
