premierstandings = ('Tottenham','West Ham','Man United','Chelsea','Liverpool','Everton','Man City','Brighton','Leicester City','Brentford','Aston Vila','Watford','Southampton','Cristal Palace','Leeds United','Burnley','Newcastle','Wolves','Norwich City','Arsenal')
print("Premier League")
print("-"*14)
print("Top 5")
print("-"*14)
for c in range(0,5):
    print(premierstandings[c])
print("-"*14)
print("Last Four")
print("-"*14)
print(premierstandings[-20:-16])
print("-"*14)
print("Teams in Alphabetic Order")
print("-"*14)
print(sorted(premierstandings))
print("-"*14)
print("Leeds United Standing")
print("-"*14)
print(f"Leeds Uniteds is on {premierstandings.index('Leeds United')+1} posintion")
